Repository ComicScrip/lyon-react-mars22-p2g1-api, pull requests merged in 2022-04, with the labels that each got.

#1 init api
  .env.example
  coords.json
  coords.txt
  init_db.sql
  package-lock.json
  package.json
  script.js
  src/app.js
  src/db-config.js
  src/environment.js
Labels: Fixed - ready for prod

#3 Creation of the route /book/:id
  src/app.js
Labels: WIP

#2 Box Routes (/all, /:id, /:CP)
  coords.json
  init_db_bal.sql
  src/app.js
Labels: Ready for prod
